### ISSUE TITLE
bug in aim trainer mode

### ISSUE THREAD

**Issue by NicholasHongGD** [DarkSnakeGang/GoogleSnakeMouseMode#10]
i didn't hit a block why the snake died

https://user-images.githubusercontent.com/94824014/172413275-e5f377ee-76ed-4c70-83a1-b12cd7f8c249.mp4

**_"What How? Meme"_**

**Comment by hwatson381** [comment]
It updates every 135ms (Or faster/slower depending on speed setting), so if you're mouse is outside the map then you will lose. Not much I can do about it. You could try with the speed settings in custom menu stuff and it might be a bit more playable.
