### ISSUE TITLE
wont work on my oculus quest 2

### ISSUE THREAD

**Issue by Malachi445** [DarkSnakeGang/GoogleSnakeMouseMode#12]
whenever i click download and try to open it in another tab it instantly closes the tab and puts it in. the files of my oculus. does anyone know how to fix

**Comment by Damianventur12** [comment]
only copy the code. and put the code in the console.

**Comment by Damianventur12** [comment]
is very easy

**Comment by hwatson381** [comment]
Yup, probably best to copy code into the console if you can't figure out a way to get the bookmarklet to work. I don't have the oculus quest 2 (or any vr headset for that matter) so I can't test it.
