### ISSUE TITLE
crash upon eating a apple in statue mode

### ISSUE THREAD

**Issue by Damianventur12** [DarkSnakeGang/GoogleSnakeMouseMode#13]

**Comment by hwatson381** [comment]
I'm aware of it, but I think it could be very difficult to fix. The best I could do is put some kind of warning that shows up before someone selects a setting that can cause a crash.

**Comment by Damianventur12** [comment]
ok :(
but add a code for the fixed
my idea is let the snake go to random grids

**Comment by Damianventur12** [comment]
won't fix

**Comment by Damianventur12** [comment]
and
