### ISSUE TITLE
T Y P E E R R O R

### ISSUE THREAD

**Issue by Damianventur12** [DarkSnakeGang/GoogleSnakeMouseMode#19]
idk
i copied the code and 
¿
![Screenshot 2023-01-01 01 12 22](https://user-images.githubusercontent.com/111714624/210160816-83516df6-86c7-493c-be5d-e7432bd28105.png)
what?

**Comment by hwatson381** [comment]
Not sure why you're getting that error, unless you're running the code on a page that isn't snake. Does the bookmark work for you?
