### ISSUE TITLE
Windows 10 Pro on Surface Go won't work

### ISSUE THREAD

**Issue by JustADudeButNot** [DarkSnakeGang/GoogleSnakeMouseMode#20]
Please I don't know what's happening, but I turn on the setting and it just doesn't work. Can you fix this?

**Comment by Corn-Dino** [comment]
Same settings do nothing

**Comment by hwatson381** [comment]
@JustADudeButNot @Corn-Dino You need to get it from here instead https://github.com/DarkSnakeGang/GoogleSnakeModLoader
