### ISSUE TITLE
crash upon eating a poison fruit

### ISSUE THREAD

**Issue by snipernate** [DarkSnakeGang/GoogleSnakeMouseMode#6]
if you eat a gray/poision fruit the game hangs/crashes the only way to fix is to reload webpage

**Comment by hwatson381** [comment]
I'm aware of this, but I don't have any plans to fix poison mode

**Comment by Damianventur12** [comment]
![what the heck](https://user-images.githubusercontent.com/111714624/188278889-646cd11d-1b9a-46c2-8caa-f57705e65c41.png)
View this

**Comment by Damianventur12** [comment]
an error. cannot fix for not code for statue and poison mode

**Comment by Ledster859** [comment]
not working on chromebook

**Comment by BOIhelv** [comment]
it broke, it doesnt work for me
