### ISSUE TITLE
Will not work

### ISSUE THREAD

**Issue by Blade04208** [DarkSnakeGang/GoogleSnakeMouseMode#9]
When putting in through bookmark or console, this error returns:

`Uncaught TypeError: Cannot read properties of null (reading '1')
    at processCode (eval at req.onload (fbx:1:178), <anonymous>:126:271)
    at XMLHttpRequest.req.onload (eval at req.onload (fbx:1:178), <anonymous>:114:9)`

That doesnt seem too good.... (。﹏。*)

**NOTE** I am doing this on the fbx version of snake (https://www.google.com/fbx?fbx=snake_arcade).

Thx, 
Blade0

**Comment by TheoCGaming** [comment]
It looks like Firefox doesn't like this bookmark.

**Comment by Blade04208** [comment]
Im doing this on MS edge ver 101.0.1210.53

**Comment by TheoCGaming** [comment]
> Im doing this on MS edge ver 101.0.1210.53

which is Chromium based. Hmmm.

**Comment by hwatson381** [comment]
Should work now :)
